version: 2

updates:
  # npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:30"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
    target-branch: "develop"
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    reviewers:
      - "BrinkhaT"
    ignore:
      # Prevent Node 21+ type definitions - stay on Node 20.x LTS
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
    groups:
      # Group patch and minor updates together
      patch-updates:
        applies-to: version-updates
        update-types:
          - "patch"
          - "minor"
      # Keep major updates separate for careful review
      major-updates:
        applies-to: version-updates
        update-types:
          - "major"

  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:30"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 3
    target-branch: "develop"
    labels:
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "ci"
      include: "scope"
    reviewers:
      - "BrinkhaT"

  # Docker base image updates
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:30"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 3
    target-branch: "develop"
    labels:
      - "docker"
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
    reviewers:
      - "BrinkhaT"
    ignore:
      # Prevent Node 21+ updates - stay on Node 20.x LTS
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]
