openapi: 3.0.3
info:
  title: Birthday Planner API
  description: API for managing and retrieving birthday data
  version: 1.0.0
  contact:
    name: Birthday Planner

servers:
  - url: http://localhost:3000/api
    description: Local development server
  - url: /api
    description: Production (relative URL)

paths:
  /birthdays:
    get:
      summary: Get all birthdays
      description: Retrieves a list of all birthdays stored in the system
      operationId: getBirthdays
      tags:
        - Birthdays
      responses:
        '200':
          description: Successful response with birthday list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BirthdayListResponse'
              examples:
                success:
                  summary: Successful response with three birthdays
                  value:
                    version: "1.0.0"
                    birthdays:
                      - id: "550e8400-e29b-41d4-a716-446655440000"
                        name: "Paula"
                        birthDate: "02.20.24"
                        createdAt: "2025-10-28T10:00:00.000Z"
                        updatedAt: "2025-10-28T10:00:00.000Z"
                      - id: "550e8400-e29b-41d4-a716-446655440001"
                        name: "Thomas"
                        birthDate: "29.08.88"
                        createdAt: "2025-10-28T10:00:00.000Z"
                        updatedAt: "2025-10-28T10:00:00.000Z"
                      - id: "550e8400-e29b-41d4-a716-446655440002"
                        name: "Isabel"
                        birthDate: "12.07.90"
                        createdAt: "2025-10-28T10:00:00.000Z"
                        updatedAt: "2025-10-28T10:00:00.000Z"
                empty:
                  summary: Empty birthday list
                  value:
                    version: "1.0.0"
                    birthdays: []
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                fileReadError:
                  summary: Failed to read birthday data file
                  value:
                    error: "Failed to load birthdays"
                    message: "Unable to read birthday data from storage"

components:
  schemas:
    Birthday:
      type: object
      required:
        - id
        - name
        - birthDate
        - createdAt
        - updatedAt
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the birthday record
          example: "550e8400-e29b-41d4-a716-446655440000"
        name:
          type: string
          minLength: 1
          maxLength: 100
          description: Name of the person
          example: "Paula"
        birthDate:
          type: string
          pattern: '^\d{2}\.\d{2}\.\d{2}$'
          description: Birth date in MM.DD.YY format
          example: "02.20.24"
        createdAt:
          type: string
          format: date-time
          description: Timestamp when the record was created (ISO-8601)
          example: "2025-10-28T10:00:00.000Z"
        updatedAt:
          type: string
          format: date-time
          description: Timestamp when the record was last updated (ISO-8601)
          example: "2025-10-28T10:00:00.000Z"

    BirthdayListResponse:
      type: object
      required:
        - version
        - birthdays
      properties:
        version:
          type: string
          pattern: '^\d+\.\d+\.\d+$'
          description: Schema version (semantic versioning)
          example: "1.0.0"
        birthdays:
          type: array
          description: Array of birthday records
          items:
            $ref: '#/components/schemas/Birthday'

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Short error message
          example: "Failed to load birthdays"
        message:
          type: string
          description: Detailed error message (optional)
          example: "Unable to read birthday data from storage"
        details:
          type: object
          description: Additional error details (optional)
          additionalProperties: true

tags:
  - name: Birthdays
    description: Operations related to birthday data
