name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      version: ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}

    steps:
      - name: Run release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  docker-build-push:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    needs: release-please
    if: needs.release-please.outputs.release_created == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version numbers
        id: version
        run: |
          VERSION="${{ needs.release-please.outputs.version }}"
          echo "full=$VERSION" >> $GITHUB_OUTPUT
          echo "major=$(echo $VERSION | cut -d. -f1)" >> $GITHUB_OUTPUT
          echo "minor=$(echo $VERSION | cut -d. -f1-2)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/birthday-planner:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/birthday-planner:${{ steps.version.outputs.full }}
            ${{ secrets.DOCKERHUB_USERNAME }}/birthday-planner:${{ steps.version.outputs.minor }}
            ${{ secrets.DOCKERHUB_USERNAME }}/birthday-planner:${{ steps.version.outputs.major }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/birthday-planner
          short-description: "Privacy-focused, self-hosted birthday planner with Docker deployment"
          readme-filepath: ./README.md

  release-summary:
    name: Release Summary
    runs-on: ubuntu-latest
    needs: [release-please, docker-build-push]
    if: always()

    steps:
      - name: Print release information
        run: |
          echo "Release created: ${{ needs.release-please.outputs.release_created }}"
          echo "Tag name: ${{ needs.release-please.outputs.tag_name }}"
          echo "Version: ${{ needs.release-please.outputs.version }}"

          if [ "${{ needs.release-please.outputs.release_created }}" == "true" ]; then
            echo "✅ Release ${{ needs.release-please.outputs.tag_name }} published successfully"
            echo "🐳 Docker images pushed to Docker Hub:"
            echo "   - brinkhat/birthday-planner:latest"
            echo "   - brinkhat/birthday-planner:${{ needs.release-please.outputs.version }}"
          else
            echo "ℹ️ No release created. Release-please is tracking changes for next release."
          fi
